package namespace

// Webapp generators (bundle webapps + the cohesive additional apps: alfresco,
// observer, stt-sidecar, onlyoffice) — split out of generator.go by service
// family. Pure code motion; the orchestrating Generate stays in generator.go.

import (
	"fmt"
	"log/slog"
	"maps"
	"sort"
	"strings"

	"github.com/citeck/citeck-launcher/internal/appdef"
	"github.com/citeck/citeck-launcher/internal/bundle"
)

var coreApps = map[string]bool{
	appdef.AppProxy: true, appdef.AppGateway: true, appdef.AppEproc: true,
	appdef.AppEmodel: true, appdef.AppUiserv: true, appdef.AppEapps: true,
	appdef.AppHistory: true, appdef.AppNotifications: true, appdef.AppTransformations: true,
}

var coreExtApps = map[string]bool{
	"integrations": true, "edi": true, appdef.AppContent: true,
}

func webappKind(name string) appdef.ApplicationKind {
	if coreApps[name] {
		return appdef.KindCiteckCore
	}
	if coreExtApps[name] {
		return appdef.KindCiteckCoreExtension
	}
	return appdef.KindCiteckAdditional
}

func generateWebapp(name string, ctx *NsGenContext) {
	// Check if explicitly disabled
	if wp, ok := ctx.Config.Webapps[name]; ok && wp.Enabled != nil && !*wp.Enabled {
		return
	}

	bundleApp, ok := ctx.Bundle.Applications[name]
	if !ok {
		return
	}

	port := ctx.NextPort()
	app := ctx.GetOrCreateApp(name)
	app.Image = bundleApp.Image
	app.Kind = webappKind(name)

	// Apply workspace default props: three-layer merge
	// Level 1: workspace-level DefaultWebappProps (global defaults for all webapps)
	// Level 2: per-app DefaultProps from workspace config
	// Level 3: namespace config overrides (applied later below)
	if ctx.WorkspaceConfig != nil {
		// Level 1: global workspace defaults
		applyWebappDefaults(app, &ctx.WorkspaceConfig.DefaultWebappProps, ctx)

		// Level 2: per-app workspace defaults
		for _, wsCfg := range ctx.WorkspaceConfig.Webapps {
			if wsCfg.ID == name {
				applyWebappDefaults(app, &wsCfg.DefaultProps, ctx)
				break
			}
		}
	}

	// Java opts from namespace config (overrides workspace defaults)
	var javaOpts string
	var springProfiles string
	var debugPort int
	if wp, ok := ctx.Config.Webapps[name]; ok { //nolint:nestif // config override logic is inherently nested
		if wp.HeapSize != "" {
			javaOpts = fmt.Sprintf("-Xmx%s -Xms%s", wp.HeapSize, wp.HeapSize)
		}
		if wp.JavaOpts != "" {
			javaOpts += " " + wp.JavaOpts
		}
		if wp.ServerPort > 0 {
			port = wp.ServerPort
		}
		if wp.Image != "" {
			app.Image = wp.Image
		}
		if wp.MemoryLimit != "" {
			app.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: wp.MemoryLimit}}
		}
		for k, v := range wp.Environments {
			app.AddEnv(k, v)
		}
		springProfiles = wp.SpringProfiles
		debugPort = wp.DebugPort
	}

	// debugPort: add JDWP agent to JAVA_OPTS (preserve workspace-set JAVA_OPTS if namespace didn't set heapSize)
	if debugPort > 0 {
		if javaOpts == "" {
			javaOpts = app.Environments["JAVA_OPTS"] // keep workspace defaults
		}
		javaOpts += fmt.Sprintf(" -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:%d", debugPort)
		app.AddPort(fmt.Sprintf("%d:%d", debugPort, debugPort))
	}

	if app.Resources == nil {
		app.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: "1g"}}
	}

	app.AddEnv("SERVER_PORT", fmt.Sprintf("%d", port))

	// Spring profiles: start with "dev,launcher", append custom profiles from config
	profiles := []string{"dev", "launcher"}
	if springProfiles != "" {
		for p := range strings.SplitSeq(springProfiles, ",") {
			p = strings.TrimSpace(p)
			if p != "" && p != "dev" && p != "launcher" {
				profiles = append(profiles, p)
			}
		}
	}
	app.AddEnv("SPRING_PROFILES_ACTIVE", strings.Join(profiles, ","))
	addWebappInfraEnv(app, ctx)
	app.AddEnv("ECOS_WEBAPP_ZOOKEEPER_HOST", ZKHost)
	// Public base URL for absolute links generated by webapps
	// (email notifications, password-reset links, etc.). Without this,
	// Spring falls back to http://localhost regardless of configured host.
	app.AddEnv("ECOS_WEBAPP_PROPERTIES_WEB_URL", ctx.ProxyBaseURL())
	app.AddEnv("ECOS_INIT_DELAY", "0")
	app.AddEnv("SPRING_CLOUD_CONFIG_ENABLED", "false") // CloudConfigServer on :8761 is for local debug only
	app.AddEnv("SPRING_CONFIG_IMPORT", "")
	app.AddEnv("ECOS_WEBAPP_WEB_AUTHENTICATORS_JWT_SECRET", ctx.Secrets.JWT)
	app.AddPort(fmt.Sprintf("%d:%d", port, port))
	app.AddDependsOn(ZKHost)
	app.AddDependsOn(RMQHost)
	// Always declare the keycloak dependency so the webapp's deployment hash
	// stays stable across auth-mode switches (KEYCLOAK ↔ BASIC). In BASIC mode
	// the keycloak container is not generated; waitForDeps treats missing deps
	// as satisfied, so startup ordering still works correctly. Without this,
	// flipping auth mode churns every webapp container unnecessarily.
	app.AddDependsOn(appdef.AppKeycloak)

	if javaOpts != "" {
		app.AddEnv("JAVA_OPTS", strings.TrimSpace(javaOpts))
	}

	processWebappDataSources(name, app, ctx)
	configureWebappProbes(name, app, ctx, port)

	// EAPPS special handling: add init containers from bundle citeckApps
	applyEappsInitContainers(name, app, ctx)

	// External SMTP for notifications app
	if ctx.Config.Email != nil && name == appdef.AppNotifications {
		applyEmailConfig(app, ctx)
	}

	// External S3 for content app
	if ctx.Config.S3 != nil && name == appdef.AppContent {
		applyS3Config(app, ctx)
	}
}

// configureWebappProbes sets startup and liveness probes for a webapp.
func configureWebappProbes(name string, app *AppBuilder, ctx *NsGenContext, port int) {
	// Startup probe: Kotlin-parity, AppProbeDef.failureThreshold default is
	// 10_000 — effectively unbounded retries. The real ceiling is the outer
	// 240s container-running wait in waitStartup; a probe-side 90×10s = 15min
	// cap silently killed long-startup webapps (Alfresco, big realm imports,
	// first-boot eapps) and left them stuck in a restart loop. Liveness keeps
	// its conservative 3-failure threshold below.
	app.StartupConditions = []appdef.StartupCondition{
		{Probe: &appdef.AppProbeDef{
			HTTP: &appdef.HTTPProbeDef{
				Path: "/management/health",
				Port: port,
			},
			PeriodSeconds:    10,
			FailureThreshold: 10000,
			TimeoutSeconds:   5,
		}},
	}

	livenessDisabled := false
	if wp, ok := ctx.Config.Webapps[name]; ok {
		livenessDisabled = wp.LivenessDisabled
	}
	if !livenessDisabled {
		app.LivenessProbe = &appdef.AppProbeDef{
			HTTP:             &appdef.HTTPProbeDef{Path: "/management/health", Port: port},
			FailureThreshold: 3,
			TimeoutSeconds:   5,
		}
	}
}

// applyEmailConfig configures external SMTP settings for the notifications app
// via environment variables. Env vars override the bundle default (SPRING_MAIL_HOST=mailhog).
func applyEmailConfig(app *AppBuilder, ctx *NsGenContext) {
	email := ctx.Config.Email
	// TLS=true → "smtps" is correct for implicit-TLS ports (465, Yandex / Rambler).
	// For STARTTLS ports (587, Gmail / Outlook / Mail.ru) the canonical protocol
	// is "smtp" with starttls.enable=true. In practice Spring's JavaMailSender
	// honors starttls.enable regardless of the protocol string, so mixing the
	// two doesn't break auth — this mapping is a long-standing simplification.
	protocol := "smtp"
	if email.TLS {
		protocol = "smtps"
	}
	app.AddEnv("SPRING_MAIL_HOST", email.Host)
	app.AddEnv("SPRING_MAIL_PORT", fmt.Sprintf("%d", email.Port))
	app.AddEnv("SPRING_MAIL_PROTOCOL", protocol)
	// Relaxed-binding equivalents of:
	//   spring.mail.properties.mail.smtp.auth: true
	//   spring.mail.properties.mail.smtp.starttls.enable: true
	// AUTH=true assumes credentials are configured; the setup wizard enforces
	// this for external SMTP. An open-relay scenario (no credentials) would
	// need this turned off — not supported here.
	app.AddEnv("SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH", "true")
	// STARTTLS is only meaningful on an encrypted connection. Forcing it on a
	// plain-text session would break delivery on ports/providers that don't
	// negotiate TLS. With TLS=true we enable it unconditionally — harmless on
	// implicit-TLS (port 465, smtps) where the handshake already happened,
	// required on STARTTLS ports (587, gmail/outlook/mail.ru).
	if email.TLS {
		app.AddEnv("SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE", "true")
	}
	app.AddEnv("ECOS_NOTIFICATIONS_EMAIL_FROM_DEFAULT", email.From)
	app.AddEnv("ECOS_NOTIFICATIONS_EMAIL_FROM_FIXED", email.From)
	// Startup-notification probe: opt-in via setup wizard. When disabled (nil
	// or Enabled=false), explicitly turn it off — the notifications service's
	// bundled application.yml has enabled=true as the built-in default, so
	// silence means "test email on every restart" which is noisy.
	if sn := email.StartupNotification; sn != nil && sn.Enabled {
		app.AddEnv("ECOS_NOTIFICATIONS_STARTUP_NOTIFICATION_ENABLED", "true")
		if sn.Recipient != "" {
			app.AddEnv("ECOS_NOTIFICATIONS_STARTUP_NOTIFICATION_RECIPIENT", sn.Recipient)
		}
	} else {
		app.AddEnv("ECOS_NOTIFICATIONS_STARTUP_NOTIFICATION_ENABLED", "false")
	}
	if email.Username != "" {
		app.AddEnv("SPRING_MAIL_USERNAME", email.Username)
	}
	if email.Password != "" {
		if pwd, err := resolveSecret(ctx.SecretReader, email.Password); err == nil {
			app.AddEnv("SPRING_MAIL_PASSWORD", pwd)
		} else {
			slog.Warn("Failed to resolve email password secret", "error", err)
		}
	}
}

// applyS3Config configures external S3 storage settings for the content app.
// Note: bucket and region are stored in namespace.yml S3Config for reference and
// configured at the app level (content-storage endpoint), not passed as env vars here.
func applyS3Config(app *AppBuilder, ctx *NsGenContext) {
	s3 := ctx.Config.S3
	app.AddEnv("ECOS_ENDPOINT_CONTENT_STORAGE_S3_ENDPOINT_URL", s3.Endpoint)
	app.AddEnv("ECOS_ENDPOINT_CONTENT_STORAGE_S3_ENDPOINT_CREDENTIALS", "content-storage-s3-credentials")
	app.AddEnv("ECOS_SECRET_CONTENT_STORAGE_S3_CREDENTIALS_TYPE", "BASIC")
	app.AddEnv("ECOS_SECRET_CONTENT_STORAGE_S3_CREDENTIALS_USERNAME", s3.AccessKey)
	if sk, err := resolveSecret(ctx.SecretReader, s3.SecretKey); err == nil {
		app.AddEnv("ECOS_SECRET_CONTENT_STORAGE_S3_CREDENTIALS_PASSWORD", sk)
	} else {
		slog.Warn("Failed to resolve S3 secret key", "error", err)
	}
}

// applyEappsInitContainers adds init containers from bundle citeckApps for the eapps service.
func applyEappsInitContainers(name string, app *AppBuilder, ctx *NsGenContext) {
	if name != appdef.AppEapps || ctx.Bundle == nil || len(ctx.Bundle.CiteckApps) == 0 {
		return
	}
	for _, citeckApp := range ctx.Bundle.CiteckApps {
		app.InitContainers = append(app.InitContainers, appdef.InitContainerDef{
			Image: citeckApp.Image,
			Environments: map[string]string{
				"ECOS_APPS_TARGET_DIR": "/run/ecos-apps",
			},
			Volumes: []string{fmt.Sprintf("./app/%s/ecos-apps:/run/ecos-apps", name)},
		})
	}
	app.AddEnv("ECOS_WEBAPP_EAPPS_ADDITIONAL_ARTIFACTS_LOCATIONS", "/run/ecos-artifacts")
	app.AddVolume(fmt.Sprintf("./app/%s/ecos-apps:/run/ecos-artifacts/app/ecosapp", name))
}

// addWebappInfraEnv sets shared infrastructure env vars (RabbitMQ host +
// credentials) on a webapp builder. Extracted from generateWebapp to keep its
// cyclomatic complexity under the linter threshold.
//
// Webapps connect to RabbitMQ as the stable "citeck" SA (not "admin"), so
// admin-password rotations don't churn the webapp container spec. The SA
// is created/synced in RabbitMQ by generateRabbitMQ's InitActions.
func addWebappInfraEnv(app *AppBuilder, ctx *NsGenContext) {
	app.AddEnv("ECOS_WEBAPP_RABBITMQ_HOST", RMQHost)
	app.AddEnv("ECOS_WEBAPP_RABBITMQ_PORT", fmt.Sprintf("%d", RMQPort))
	if ctx.Secrets.CiteckSA != "" {
		app.AddEnv("ECOS_WEBAPP_RABBITMQ_USERNAME", CiteckSAUser)
		app.AddEnv("ECOS_WEBAPP_RABBITMQ_PASSWORD", ctx.Secrets.CiteckSA)
	}
}

// applyWebappDefaults applies a WebappDefaultProps layer to an app builder.
func applyWebappDefaults(app *AppBuilder, props *bundle.WebappDefaultProps, ctx *NsGenContext) {
	if props == nil {
		return
	}
	if props.Image != "" {
		app.Image = props.Image
	}
	for k, v := range props.Environments {
		app.AddEnv(k, resolveTemplateVarsWithContext(v, ctx))
	}
	if props.HeapSize != "" {
		app.AddEnv("JAVA_OPTS", fmt.Sprintf("-Xmx%s -Xms%s", props.HeapSize, props.HeapSize))
	}
	if props.MemoryLimit != "" {
		app.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: props.MemoryLimit}}
	}
}

// processWebappDataSources reads datasource definitions from workspace config
// and generates:
//   - Spring cloud config YAML (application-launcher.yml) with all datasource URLs
//   - Volume mount for the config file
//   - SPRING_CONFIG_ADDITIONALLOCATION env var
//   - Init actions on postgres to create databases
//   - Dependencies on postgres/mongodb
//   - extCloudConfig for CloudConfigServer (datasources with localhost URLs + published ports)
//
// This mirrors the Kotlin NamespaceGenerator.processDataSource + cloud config logic.
func processWebappDataSources(appName string, app *AppBuilder, ctx *NsGenContext) {
	if ctx.WorkspaceConfig == nil {
		return
	}

	// Find webapp datasources: workspace defaults, then namespace overrides on top
	dataSources := make(map[string]bundle.DataSourceConfig)
	for _, webapp := range ctx.WorkspaceConfig.Webapps {
		if webapp.ID == appName {
			maps.Copy(dataSources, webapp.DefaultProps.DataSources)
			break
		}
	}
	// Namespace-level dataSources override workspace defaults
	if wp, ok := ctx.Config.Webapps[appName]; ok {
		maps.Copy(dataSources, wp.DataSources)
	}

	pgApp := ctx.Applications[appdef.AppPostgres]

	// Build cloud config maps for both local (webappCloudConfig) and external (extCloudConfig)
	webappCloudConfig := make(map[string]any)
	extCloudConfig := make(map[string]any)

	// Sort datasource keys for deterministic iteration — postgres InitActions
	// are appended in iteration order and feed into the deployment hash. A
	// random map walk on a no-op reload would produce a different action
	// ordering, hash-bust postgres, and trigger a spurious recreate.
	dsKeys := make([]string, 0, len(dataSources))
	for k := range dataSources {
		dsKeys = append(dsKeys, k)
	}
	sort.Strings(dsKeys)
	for _, dsKey := range dsKeys {
		dsCfg := dataSources[dsKey]
		url := resolveTemplateVars(dsCfg.URL)
		dsPrefix := "ecos.webapp.dataSources." + dsKey

		if strings.HasPrefix(url, "jdbc:") { //nolint:nestif // datasource config wiring
			app.AddDependsOn(appdef.AppPostgres)
			dbName := extractDBName(url)

			// Add init action on postgres to create DB
			if dbName != "" && pgApp != nil {
				pgApp.InitActions = append(pgApp.InitActions, appdef.AppInitAction{
					Exec: []string{"sh", "-c", "/init_db_and_user.sh " + dbName},
				})
			}

			// Local config (container-to-container URLs)
			webappCloudConfig[dsPrefix+".url"] = url
			if dbName != "" {
				webappCloudConfig[dsPrefix+".username"] = dbName
				webappCloudConfig[dsPrefix+".password"] = dbName
			}
			if dsCfg.XA {
				webappCloudConfig[dsPrefix+".xa"] = true
			}

			// Ext config (localhost URLs with published ports, for local debugging)
			extURL := rewriteDataSourceURLForLocalhost(url, "jdbc:")
			extCloudConfig[dsPrefix+".url"] = extURL
			if dbName != "" {
				extCloudConfig[dsPrefix+".username"] = dbName
				extCloudConfig[dsPrefix+".password"] = dbName
			}

			// Also set env vars for "main" datasource (Spring Boot standard)
			if dsKey == "main" {
				app.AddEnv("SPRING_DATASOURCE_USERNAME", dbName)
				app.AddEnv("SPRING_DATASOURCE_PASSWORD", dbName)
				app.AddEnv("SPRING_DATASOURCE_URL", url)
			}
		} else if strings.HasPrefix(url, "mongodb:") {
			app.AddDependsOn(appdef.AppMongodb)

			webappCloudConfig[dsPrefix+".url"] = url
			extCloudConfig[dsPrefix+".url"] = rewriteDataSourceURLForLocalhost(url, "mongodb:")

			app.AddEnv("SPRING_DATA_MONGODB_URI", url)
		}
	}

	// Three-level cloudConfig merge in priority order (each layer's values
	// override / deep-merge into earlier ones). Mirrors the Kotlin merge from
	// generateWebapp:
	//   1. workspace.defaultWebappProps.cloudConfig — global webapp defaults.
	//   2. workspace.webapps[appName].defaultProps.cloudConfig — per-app
	//      workspace defaults.
	//   3. namespace.webapps[appName].cloudConfig — per-app namespace override.
	// Object values are deep-merged; scalars are last-write-wins. Without this
	// loop, per-workspace overrides (e.g. UI-managed licenses pinned at the
	// workspace level, ai.callRecording config defaults) silently dropped to
	// the namespace level and never reached the running webapps.
	if ctx.WorkspaceConfig != nil {
		if ctx.WorkspaceConfig.DefaultWebappProps.CloudConfig != nil {
			deepMergeMaps(webappCloudConfig, ctx.WorkspaceConfig.DefaultWebappProps.CloudConfig)
		}
		for _, wsWp := range ctx.WorkspaceConfig.Webapps {
			if wsWp.ID == appName {
				if wsWp.DefaultProps.CloudConfig != nil {
					deepMergeMaps(webappCloudConfig, wsWp.DefaultProps.CloudConfig)
				}
				break
			}
		}
	}
	if wp, ok := ctx.Config.Webapps[appName]; ok {
		deepMergeMaps(webappCloudConfig, wp.CloudConfig)
	}

	// License and bundle-key injection for eapps.
	// Merge user-added licenses (from license.Service / encrypted store) with
	// workspace-declared ones. UI licenses take precedence by ID; the merged
	// list is sorted by descending Priority so the highest-priority license
	// is first — matches license.Service.List() semantics consumed by the UI.
	if appName == appdef.AppEapps && ctx.WorkspaceConfig != nil {
		mergedLicenses := mergeLicenses(ctx.WorkspaceConfig.Licenses, ctx.ExtraLicenses)
		injectLicensesAndBundleKey(mergedLicenses, ctx.Bundle, webappCloudConfig, extCloudConfig)
	}

	// Always write cloud config YAML and mount props directory (matching Kotlin behavior).
	// Even when empty, the mount must exist for hand-placed Spring config files.
	configPath := fmt.Sprintf("app/%s/props/application-launcher.yml", appName)
	if len(webappCloudConfig) > 0 {
		ctx.Files[configPath] = []byte(flatMapToYAML(webappCloudConfig))
	} else {
		ctx.Files[configPath] = []byte("{}\n")
	}
	app.AddEnv("SPRING_CONFIG_ADDITIONALLOCATION", "/run/java.io/spring-props/")
	app.AddVolume(fmt.Sprintf("./app/%s/props:/run/java.io/spring-props/", appName))

	// Store ext cloud config for CloudConfigServer
	if len(extCloudConfig) > 0 {
		ctx.CloudConfig[appName] = extCloudConfig
	}
}

func generateAlfresco(ctx *NsGenContext) {
	if ctx.WorkspaceConfig == nil || !ctx.WorkspaceConfig.Alfresco.Enabled {
		return
	}

	// Check bundle has an Alfresco image before registering any containers
	alfImage := bundleImageOr(ctx, appdef.AppAlfresco, "")
	if alfImage == "" {
		return
	}

	// 1. Alfresco Postgres (separate from main postgres)
	alfPg := ctx.GetOrCreateApp(appdef.AppAlfPostgres)
	alfPg.Image = "postgres:9.4"
	alfPg.Kind = appdef.KindThirdParty
	alfPg.AddEnv("POSTGRES_USER", "postgres")
	alfPg.AddEnv("POSTGRES_PASSWORD", "postgres")
	alfPg.AddEnv("PGDATA", "/var/lib/postgresql/data")
	alfPg.AddPort("54329:5432")
	alfPg.AddVolume("alf_postgres:/var/lib/postgresql/data")
	alfPg.AddVolume("./postgres/init_db_and_user.sh:/init_db_and_user.sh")
	alfPg.InitActions = []appdef.AppInitAction{
		{Exec: []string{"sh", "-c", "/init_db_and_user.sh alfresco"}},
		{Exec: []string{"sh", "-c", "/init_db_and_user.sh alf_flowable"}},
	}
	alfPg.StartupConditions = []appdef.StartupCondition{
		{Log: &appdef.LogStartupCondition{Pattern: ".*database system is ready to accept connections.*"}},
		{Probe: &appdef.AppProbeDef{Exec: &appdef.ExecProbeDef{
			Command: []string{"/bin/sh", "-c", "psql -U postgres -d postgres -c 'SELECT 1' || exit 1"},
		}}},
	}
	alfPg.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: "512m"}}

	// 2. Alfresco app
	alfApp := ctx.GetOrCreateApp(appdef.AppAlfresco)
	alfApp.Image = alfImage
	alfApp.Kind = appdef.KindCiteckAdditional
	alfPort := 17019 // fixed port for alfresco — not part of webapp counter
	alfApp.AddPort(fmt.Sprintf("%d:8080", alfPort))
	alfApp.AddDependsOn(appdef.AppAlfPostgres)
	alfApp.AddVolume("alf_content:/content")
	alfApp.AddVolume("./alfresco/alfresco_additional.properties:/tmp/alfresco/alfresco_additional.properties")
	alfApp.StartupConditions = []appdef.StartupCondition{
		{Probe: &appdef.AppProbeDef{HTTP: &appdef.HTTPProbeDef{Path: "/alfresco/s/citeck/ecos/eureka-status", Port: 8080}}},
	}
	alfApp.AddEnv("ALFRESCO_USER_STORE_ADMIN_PASSWORD", "fefdbb615556a4b1dbb36e7935d77cf2")
	alfApp.AddEnv("USE_EXTERNAL_AUTH", "true")
	alfApp.AddEnv("SOLR_HOST", appdef.AppAlfSolr)
	alfApp.AddEnv("SOLR_PORT", "8080")
	alfApp.AddEnv("DB_HOST", appdef.AppAlfPostgres)
	alfApp.AddEnv("DB_PORT", "5432")
	alfApp.AddEnv("DB_NAME", "alfresco")
	alfApp.AddEnv("DB_USERNAME", "alfresco")
	alfApp.AddEnv("DB_PASSWORD", "alfresco")
	alfApp.AddEnv("ALFRESCO_HOSTNAME", appdef.AppAlfresco)
	alfApp.AddEnv("ALFRESCO_PROTOCOL", "http")
	alfApp.AddEnv("SHARE_HOSTNAME", appdef.AppAlfresco)
	alfApp.AddEnv("SHARE_PROTOCOL", "http")
	alfApp.AddEnv("SHARE_PORT", "80")
	alfApp.AddEnv("ALFRESCO_PORT", "8080")
	alfApp.AddEnv("FLOWABLE_URL", "http://localhost")
	alfApp.AddEnv("MAIL_HOST", MailhogHost)
	alfApp.AddEnv("MAIL_PORT", "1025")
	alfApp.AddEnv("MAIL_FROM_DEFAULT", "citeck@ecos24.ru")
	alfApp.AddEnv("MAIL_PROTOCOL", "smtp")
	alfApp.AddEnv("MAIL_SMTP_AUTH", "false")
	alfApp.AddEnv("MAIL_SMTP_STARTTLS_ENABLE", "false")
	alfApp.AddEnv("MAIL_SMTPS_AUTH", "false")
	alfApp.AddEnv("MAIL_SMTPS_STARTTLS_ENABLE", "false")
	alfApp.AddEnv("FLOWABLE_DB_HOST", appdef.AppAlfPostgres)
	alfApp.AddEnv("FLOWABLE_DB_PORT", "5432")
	alfApp.AddEnv("FLOWABLE_DB_NAME", "alf_flowable")
	alfApp.AddEnv("FLOWABLE_DB_USERNAME", "alf_flowable")
	alfApp.AddEnv("FLOWABLE_DB_PASSWORD", "alf_flowable")
	alfApp.AddEnv("JAVA_OPTS", "-Xms4G -Xmx4G -Duser.country=EN -Duser.language=en -Djava.security.egd=file:///dev/urandom -Djavamelody.authorized-users=admin:admin")

	// Substitute RMQ credentials in alfresco properties (embedded appfile
	// has hardcoded "admin" — replace with the generated admin password).
	alfPropsKey := "alfresco/alfresco_additional.properties"
	if alfProps, ok := ctx.Files[alfPropsKey]; ok && ctx.Secrets.AdminPassword != "" {
		updated := strings.ReplaceAll(string(alfProps),
			"rabbitmq.export.server.password=admin", "rabbitmq.export.server.password="+ctx.Secrets.AdminPassword)
		updated = strings.ReplaceAll(updated,
			"rabbitmq.server.password=admin", "rabbitmq.server.password="+ctx.Secrets.AdminPassword)
		ctx.Files[alfPropsKey] = []byte(updated)
	}

	// 3. Alfresco Solr
	alfSolr := ctx.GetOrCreateApp(appdef.AppAlfSolr)
	alfSolr.Image = "nexus.citeck.ru/ess:1.1.0"
	alfSolr.Kind = appdef.KindCiteckAdditional
	alfSolr.AddPort("38080:8080")
	alfSolr.AddVolume("alf_solr_data:/opt/solr4_data")
	alfSolr.AddEnv("TWEAK_SOLR", "true")
	alfSolr.AddEnv("JAVA_OPTS", "-Xms1G -Xmx1G")
	alfSolr.AddEnv("ALFRESCO_HOST", appdef.AppAlfresco)
	alfSolr.AddEnv("ALFRESCO_PORT", "8080")
	alfSolr.AddEnv("ALFRESCO_INDEX_TRANSFORM_CONTENT", "false")
	alfSolr.AddEnv("ALFRESCO_RECORD_UNINDEXED_NODES", "false")
	alfSolr.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: "1g"}}
}

func generateObserver(ctx *NsGenContext) {
	if !ctx.Config.Observer.Enabled {
		return
	}

	obsImage := ctx.Config.Observer.Image
	if obsImage == "" {
		obsImage = bundleImageOr(ctx, appdef.AppObserver, "citeck/observer:1.1.0")
	}

	const (
		// Observer ports: 17014–17017 (KC mgmt 17013 sits below; ZK admin 17018, Alfresco 17019, webapps 17020+)
		obsLogUDP   = 17014 // UDP log receiver
		obsOTLPHTTP = 17015 // OTLP HTTP/protobuf receiver
		obsHTTP     = 17016 // HTTP API + embedded UI
		obsGRPC     = 17017 // OTLP gRPC receiver
		obsPGPort   = 14524 // published port for observer-postgres (local debugging)
		obsDBName   = "observer"
		obsDBUser   = "observer"
		obsDBPass   = "observer"
	)

	// 1. Observer Postgres — separate instance tuned for observability workload:
	// heavy writes (span/metric ingestion), aggregation queries, JSONB GIN lookups
	obsPg := ctx.GetOrCreateApp(appdef.AppObsPostgres)
	obsPg.Image = "postgres:18"
	obsPg.Kind = appdef.KindThirdParty
	obsPg.AddEnv("POSTGRES_DB", obsDBName)
	obsPg.AddEnv("POSTGRES_USER", obsDBUser)
	obsPg.AddEnv("POSTGRES_PASSWORD", obsDBPass)
	obsPg.AddEnv("PGDATA", "/var/lib/postgresql/data")
	obsPg.AddPort(fmt.Sprintf("%d:%d", obsPGPort, PGPort))
	obsPg.AddVolume("obs_postgres:/var/lib/postgresql/data")
	obsPg.Cmd = []string{
		"-c", "shared_buffers=256MB",
		"-c", "work_mem=32MB",
		"-c", "maintenance_work_mem=128MB",
		"-c", "effective_cache_size=1GB",
		"-c", "random_page_cost=1.1",
		"-c", "checkpoint_completion_target=0.9",
		"-c", "wal_buffers=16MB",
		"-c", "max_wal_size=1GB",
		"-c", "min_wal_size=256MB",
	}
	obsPg.StartupConditions = []appdef.StartupCondition{
		{Log: &appdef.LogStartupCondition{Pattern: ".*database system is ready to accept connections.*"}},
		{Probe: &appdef.AppProbeDef{
			Exec: &appdef.ExecProbeDef{
				Command: []string{"/bin/sh", "-c", fmt.Sprintf("pg_isready -U %s || exit 1", obsDBUser)},
			},
			PeriodSeconds:    10,
			FailureThreshold: 60,
			TimeoutSeconds:   5,
		}},
	}
	obsPg.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: "512m"}}
	obsPg.LivenessProbe = &appdef.AppProbeDef{
		Exec:             &appdef.ExecProbeDef{Command: []string{"pg_isready", "-U", obsDBUser}},
		FailureThreshold: 3,
		TimeoutSeconds:   5,
	}

	// 2. citeck-observer — env var names match the observer's Config struct
	// (reflection-based: database.host → DATABASE_HOST, zookeeper.hosts → ZOOKEEPER_HOSTS, etc.)
	obs := ctx.GetOrCreateApp(appdef.AppObserver)
	obs.Image = obsImage
	obs.Kind = appdef.KindThirdParty

	// Core server — all ports explicit (don't rely on observer defaults)
	obs.AddEnv("SERVER_MODE", "dev")
	obs.AddEnv("SERVER_PORT", fmt.Sprintf("%d", obsHTTP))
	obs.AddEnv("OTLP_GRPC_PORT", fmt.Sprintf("%d", obsGRPC))
	obs.AddEnv("OTLP_HTTP_PORT", fmt.Sprintf("%d", obsOTLPHTTP))
	obs.AddEnv("LOG_RECEIVER_UDP_PORT", fmt.Sprintf("%d", obsLogUDP))

	// Observer's own database
	obs.AddEnv("DATABASE_HOST", ObsPGHost)
	obs.AddEnv("DATABASE_PORT", fmt.Sprintf("%d", PGPort))
	obs.AddEnv("DATABASE_NAME", obsDBName)
	obs.AddEnv("DATABASE_USER", obsDBUser)
	obs.AddEnv("DATABASE_PASSWORD", obsDBPass)
	obs.AddEnv("DATABASE_TLS_SSL_MODE", "disable")

	// ZooKeeper discovery
	obs.AddEnv("ZOOKEEPER_HOSTS", fmt.Sprintf("%s:%d", ZKHost, ZKPort))
	obs.AddEnv("DISCOVERY_HOST", appdef.AppObserver)
	obs.AddEnv("DISCOVERY_APP_NAME", appdef.AppObserver)

	// Auth — same JWT secret as all webapps
	obs.AddEnv("AUTH_JWT_SECRET", ctx.Secrets.JWT)
	obs.AddEnv("CORS_ALLOWED_ORIGINS", "*")

	// Infrastructure monitoring — RabbitMQ via Management API. Uses the
	// stable "citeck" SA (monitoring tag) so admin-password rotations don't
	// invalidate observer's credentials.
	obs.AddEnv("RMQ_MONITOR_ENABLED", "true")
	obs.AddEnv("RMQ_MONITOR_URL", fmt.Sprintf("http://%s:15672", RMQHost))
	obsRMQUser := "admin"
	obsRMQPass := ctx.Secrets.AdminPasswordOrDefault()
	if ctx.Secrets.CiteckSA != "" {
		obsRMQUser = CiteckSAUser
		obsRMQPass = ctx.Secrets.CiteckSA
	}
	obs.AddEnv("RMQ_MONITOR_USER", obsRMQUser)
	obs.AddEnv("RMQ_MONITOR_PASSWORD", obsRMQPass)

	// Infrastructure monitoring — PostgreSQL via pg_stat views
	obs.AddEnv("PG_MONITOR_ENABLED", "true")
	pgTarget := fmt.Sprintf(`[{"name":"citeck","host":"%s","port":%d,"user":"postgres","password":"postgres"}]`, PGHost, PGPort) //nolint:gocritic // sprintfQuotedString: JSON template requires literal quotes, not %q
	obs.AddEnv("PG_MONITOR_TARGETS", pgTarget)

	// Infrastructure monitoring — ZooKeeper via "mntr" command
	obs.AddEnv("ZK_MONITOR_ENABLED", "true")
	obs.AddEnv("ZK_MONITOR_HOSTS", fmt.Sprintf("%s:%d", ZKHost, ZKPort))

	obs.AddPort(fmt.Sprintf("%d:%d", obsHTTP, obsHTTP))
	obs.AddPort(fmt.Sprintf("%d:%d", obsGRPC, obsGRPC))
	obs.AddPort(fmt.Sprintf("%d:%d", obsOTLPHTTP, obsOTLPHTTP))
	obs.AddPort(fmt.Sprintf("%d:%d/udp", obsLogUDP, obsLogUDP))
	obs.AddDependsOn(appdef.AppObsPostgres)
	obs.AddDependsOn(appdef.AppZookeeper)
	obs.StartupConditions = []appdef.StartupCondition{
		{Probe: &appdef.AppProbeDef{
			HTTP:             &appdef.HTTPProbeDef{Path: "/health", Port: obsHTTP},
			PeriodSeconds:    10,
			FailureThreshold: 30,
			TimeoutSeconds:   5,
		}},
	}
	obs.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: "512m"}}
	obs.LivenessProbe = &appdef.AppProbeDef{
		HTTP:             &appdef.HTTPProbeDef{Path: "/health", Port: obsHTTP},
		FailureThreshold: 3,
		TimeoutSeconds:   5,
	}

	// 3. Cloud config for CloudConfigServer (local debugging: "stop in launcher, run locally")
	extCloudConfig := map[string]any{
		// Server — explicit ports for local debugging
		"server.port":           obsHTTP,
		"otlp.grpc_port":        obsGRPC,
		"otlp.http_port":        obsOTLPHTTP,
		"log_receiver.udp_port": obsLogUDP,
		// Observer's own database (localhost with published port)
		"database.host":         "localhost",
		"database.port":         obsPGPort,
		"database.name":         obsDBName,
		"database.user":         obsDBUser,
		"database.password":     obsDBPass,
		"database.tls.ssl_mode": "disable",
		// ZooKeeper
		"zookeeper.hosts": "localhost:2181",
		// Auth
		"auth.jwt_secret": ctx.Secrets.JWT,
		// Infrastructure monitoring — RabbitMQ (citeck SA; see above)
		"rmq_monitor.enabled":  true,
		"rmq_monitor.url":      "http://localhost:15672",
		"rmq_monitor.user":     obsRMQUser,
		"rmq_monitor.password": obsRMQPass,
		// Infrastructure monitoring — ZooKeeper
		"zk_monitor.enabled": true,
		"zk_monitor.hosts":   "localhost:2181",
		// Infrastructure monitoring — main PostgreSQL (webapp databases)
		"pg_monitor.enabled": true,
	}
	ctx.CloudConfig[appdef.AppObserver] = extCloudConfig
}

// STT sidecar defaults — match the Kotlin SttSidecarProps.DEFAULT:
//   - port 14080 lives in the infrastructure cluster (below the 17020+
//     dynamic webapp range), so it never collides with a counter-allocated
//     port even when AI is the first or last webapp generated.
//   - 2g memory limit matches the gigaam STT model footprint; smaller
//     limits trigger OOM on first transcript.
const (
	sttSidecarDefaultPort   = 14080
	sttSidecarDefaultMemory = "2g"
)

// generateSttSidecar adds the STT (speech-to-text) websocket-proxy sidecar
// for the AI app. Kotlin parity, see SttSidecarProps + NamespaceGenerator
// .generateSttSidecar in v1.4+. Behavior:
//   - No AI app in the generated set → no STT (it only serves AI).
//   - AI detached → no STT at all; the AI runtime stays put.
//   - STT detached → the STT spec is still generated (so the user can re-attach
//     it from the UI without losing the AppRuntime), but the AI app does NOT
//     get the env var or dependency so AI keeps starting without the sidecar.
//   - Image: workspaceConfig.sttSidecar.image wins; else bundle's stt-sidecar
//     image; else skip (no image = nothing to deploy).
//   - HTTP startup probe at /health on the container port — same probe Kotlin
//     uses, gated by the standard outer 240s running-state wait.
func generateSttSidecar(ctx *NsGenContext) {
	aiApp, ok := ctx.Applications[appdef.AppAi]
	if !ok {
		return
	}
	if ctx.DetachedApps[appdef.AppAi] {
		// AI off the table → STT serves nothing.
		return
	}

	props := bundle.SttSidecarProps{}
	if ctx.WorkspaceConfig != nil && ctx.WorkspaceConfig.SttSidecar != nil {
		props = *ctx.WorkspaceConfig.SttSidecar
	}

	port := props.Port
	if port <= 0 {
		port = sttSidecarDefaultPort
	}
	memoryLimit := props.MemoryLimit
	if memoryLimit == "" {
		memoryLimit = sttSidecarDefaultMemory
	}

	image := props.Image
	if image == "" && ctx.Bundle != nil {
		if bundleApp, exists := ctx.Bundle.Applications[appdef.AppSttSidecar]; exists {
			image = bundleApp.Image
		}
	}
	if image == "" {
		// Nothing to deploy. AI keeps running; the env var simply isn't set
		// (the AI app falls back to its built-in defaults, same as Kotlin).
		return
	}

	stt := ctx.GetOrCreateApp(appdef.AppSttSidecar)
	stt.Image = image
	stt.Kind = appdef.KindCiteckAdditional
	stt.AddEnv("PORT", fmt.Sprintf("%d", port))
	stt.AddPort(fmt.Sprintf("%d:%d", port, port))
	stt.AddVolume("stt_models:/root/.cache/gigaam")
	stt.StartupConditions = []appdef.StartupCondition{
		{Probe: &appdef.AppProbeDef{
			HTTP:             &appdef.HTTPProbeDef{Path: "/health", Port: port},
			PeriodSeconds:    10,
			FailureThreshold: 10000, // Kotlin-parity: effectively unbounded; outer 240s wait is the real ceiling
			TimeoutSeconds:   5,
		}},
	}
	stt.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: memoryLimit}}

	if !ctx.DetachedApps[appdef.AppSttSidecar] {
		// Wire AI → STT only when both are active. Detached STT keeps its spec
		// so a future re-attach is one click away, but AI must not block on a
		// disabled sidecar.
		aiApp.AddEnv("CITECK_AI_CALLRECORDING_STT_SIDECARURL",
			fmt.Sprintf("http://%s:%d", appdef.AppSttSidecar, port))
		aiApp.AddDependsOn(appdef.AppSttSidecar)
	}
}

func generateOnlyOffice(ctx *NsGenContext) {
	fallback := "onlyoffice/documentserver:9.1.0.1"
	memLimit := "3g"
	if ctx.WorkspaceConfig != nil {
		if ctx.WorkspaceConfig.OnlyOffice.Image != "" {
			fallback = ctx.WorkspaceConfig.OnlyOffice.Image
		}
		if ctx.WorkspaceConfig.OnlyOffice.MemoryLimit != "" {
			memLimit = ctx.WorkspaceConfig.OnlyOffice.MemoryLimit
		}
	}
	img := bundleImageOr(ctx, appdef.AppOnlyoffice, fallback)
	app := ctx.GetOrCreateApp(appdef.AppOnlyoffice)
	app.Image = img
	app.Kind = appdef.KindThirdParty
	app.AddEnv("JWT_ENABLED", "false")
	app.AddEnv("ALLOW_PRIVATE_IP_ADDRESS", "true")
	app.AddPort("8070:80")
	app.Resources = &appdef.AppResourcesDef{Limits: appdef.LimitsDef{Memory: memLimit}}
}
