package appfiles

import (
	"embed"
	"fmt"
)

// The HotSpot attach client that runs INSIDE a container, executed by the
// image's own java. The .class is committed rather than compiled during the Go
// build: neither the build nor CI may depend on a JDK. checksums.sha256 (also
// committed, generated by `make jvm-attach-class`) is what keeps the class in
// step with its source — see TestAttachClassMatchesSource.
//
//go:embed embedded/jvm/CiteckAttach.class embedded/jvm/CiteckAttach.java embedded/jvm/checksums.sha256
var jvmAttachFS embed.FS

// AttachClassName is the class name the client must be invoked with, and the
// file name it must be copied in as: `java -cp <dir> CiteckAttach <pid|0> <cmd>`.
const AttachClassName = "CiteckAttach"

// AttachClassFileName is the file name inside the container. The JVM resolves a
// class by file name, so this cannot be given a launcher-specific prefix.
const AttachClassFileName = AttachClassName + ".class"

// AttachClass returns the compiled attach client.
func AttachClass() ([]byte, error) {
	data, err := jvmAttachFS.ReadFile("embedded/jvm/" + AttachClassFileName)
	if err != nil {
		return nil, fmt.Errorf("read embedded attach class: %w", err)
	}
	return data, nil
}

// attachSource and attachChecksums back the drift test; they are embedded so the
// check runs against exactly the bytes that shipped, not against whatever the
// working tree happens to hold.
func attachSource() ([]byte, error) {
	data, err := jvmAttachFS.ReadFile("embedded/jvm/" + AttachClassName + ".java")
	if err != nil {
		return nil, fmt.Errorf("read embedded attach source: %w", err)
	}
	return data, nil
}

func attachChecksums() ([]byte, error) {
	data, err := jvmAttachFS.ReadFile("embedded/jvm/checksums.sha256")
	if err != nil {
		return nil, fmt.Errorf("read embedded attach checksums: %w", err)
	}
	return data, nil
}
